services:
  app:
    platform: ${PLATFORM}
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: app
    tty: true
    restart: always
    volumes:
      - $PWD/docs:/srv/jekyll
    networks:
      - frontend
    ports:
      - 4000:4000
    command: >
      bash -c "bundle install &&
      bundle exec jekyll serve --host 0.0.0.0 --livereload"
networks:
  frontend:
    driver: bridge
