services:
  app:
    platform: ${PLATFORM}
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - WORK_DIR=${WORK_DIR}
        - PORT=${PORT}
    container_name: app
    tty: true
    volumes:
      - ./:/${WORK_DIR}:delegated
      - /${WORK_DIR}/node_modules
    ports:
      - ${PORT}:${PORT}
    environment:
      - NODE_ENV=${NODE_ENV}
