services:
  app:
    platform: ${PLATFORM}
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        - WORK_DIR=${WORK_DIR}
        - PORT=${PORT}
        - NODE_ENV=${NODE_ENV}
    container_name: app
    tty: true
    volumes:
      - ./:/${WORK_DIR}:delegated
      - ${WORK_DIR}/node_modules
      - ${WORK_DIR}/.yarn
      - ${WORK_DIR}/.cache
    ports:
      - ${PORT}:${PORT}
    environment:
      - NODE_ENV=${NODE_ENV}

